# .streamlit/config.toml
[theme]
primaryColor = "#96cbeeff"
backgroundColor = "#9bb1b0ff"
secondaryBackgroundColor = "#ffffff"
textColor = "#134e4a"
font = "sans serif"

[browser]
gatherUsageStats = false

# Force wide mode at the client level
[client]
wideMode = true

# Optional: Set default viewing mode
[runner]
magicEnabled = true

# Optional: Server settings
[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true
